python3 model_moments_kfold.py 1 2
python3 model_moments_kfold.py 1 3
python3 model_moments_kfold.py 1 4
python3 model_moments_kfold.py 1 5
python3 model_moments_kfold.py 1 6
python3 model_moments_kfold.py 2 3
python3 model_moments_kfold.py 2 4
python3 model_moments_kfold.py 2 5
python3 model_moments_kfold.py 2 6
python3 model_moments_kfold.py 3 4
python3 model_moments_kfold.py 3 5
python3 model_moments_kfold.py 3 6
python3 model_moments_kfold.py 4 5
python3 model_moments_kfold.py 4 6
python3 model_moments_kfold.py 5 6
